content:
  application/json:
    schema:
      properties:
        definitions:
          items:
            properties:
              options:
                items:
                  type: string
              fields:
                items:
                  type: object
                  properties:
                    key:
                      type: string
                    name:
                      type: string
                    description:
                      type: string
                    type:
                      type: string
                    options:
                      type: array
                      items:
                        type: string
